# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sha_Uber_App_MVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sha_Uber_App_MVVM
#	pod 'Firebase/Core'
  pod 'Firebase/Firestore'
	pod 'Firebase/Database'
	pod 'Firebase/Auth'
	pod 'Firebase/Storage'
	pod 'GeoFire', '>= 1.1'

end
